# Generated by Django 5.2.6 on 2025-09-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gokart', '0018_alter_orderplaced_payment_alter_orderplaced_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='product/banner'),
        ),
    ]
