# Generated by Django 5.2.6 on 2025-09-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gokart', '0019_alter_banner_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='brands', to='Gokart.category'),
        ),
    ]
